apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/1-nodejs/base
- components/demo-app/base
- components/hacbs-nodejs/base
- components/java-quarkus-with-env/base
- components/java-quarkus/base
- components/new-quarkus/base
- components/nodejs-sample/base
- components/nodejs/base
- components/test-quarkus/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
