apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-nodejs
    app.kubernetes.io/part-of: purple-mermaid-app
  name: hacbs-nodejs
  namespace: karthik-jk
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: hacbs-nodejs
status:
  loadBalancer: {}
