apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-quarkus
    app.kubernetes.io/part-of: purple-mermaid-app
  name: test-quarkus
  namespace: karthik-jk
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test-quarkus
status:
  loadBalancer: {}
